import Head from "next/head";
import Image from "next/image";

import { dehydrate, QueryClient, useQuery } from "react-query";

type SpaceXData = {
  name: string;
  links: {
    patch: {
      large: string;
    };
  };
};

const getSpaceXData = async () =>
  await (await fetch("https://api.spacexdata.com/v5/launches/latest")).json();

export default function Home() {
  const { data, isLoading, isFetching } = useQuery<SpaceXData>(
    "spacex",
    getSpaceXData
  );
  console.log(data);

  if (isLoading) return <div>Loading...</div>;

  if (!data) return <div>No Data!</div>;

  return (
    <div className="">
      <Head>
        <title>Space X Data</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="grid place-items-center h-screen">
        <h1 className="text-sm uppercase font-bold animate-pulse">
          Space X Data
        </h1>
        <div className="grid place-items-center my-4">
          <h1 className="lg:text-8xl py-4">{data?.name}</h1>
          <Image
            src={data?.links.patch.large}
            alt="patch-image"
            width={200}
            height={200}
            className="my-12"
          />
        </div>
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const queryClient = new QueryClient();
  await queryClient.prefetchQuery<SpaceXData>("spacex", getSpaceXData);

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
}
